# git clone https://github.com/getredash/redash
# docker build -t="th9976/redash" . --build-arg http_proxy=http://10.10.10.106:1080 --build-arg https_proxy=http://10.10.10.106:1080
# https://redash.io/help/open-source/admin-guide/env-vars-settings
# docker-compose -f redash-compose.yml run --rm server create_db
version: '2'
services:
  server:
    image: th9976/redash
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    env_file:
      - ./redash.env
    restart: always
    
  scheduler:
    image: th9976/redash
    command: scheduler
    env_file:
      - ./redash.env
    restart: always

  worker:
    image: th9976/redash
    command: worker
    env_file:
      - ./redash.env
    restart: always
  
  redis:
    image: redis
    ports:
     - "6379:6379"
    volumes: 
      - ./data/redis_data:/data
    restart: always

  postgres:
    image: postgres
    ports:
     - "5432:5432"
    env_file:
      - ./redash.env
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data
    restart: always