server.port: 32002
spring.profiles.active: dev
server.shutdown: graceful

# endpoints
# management.endpoints.web.exposure.include: *

# eureka
eureka.instance.prefer-ip-address: true
eureka.instance.instance-id: ${spring.cloud.client.ip-address}:${server.port}
eureka.client.serviceUrl.defaultZone: http://discovery-server-0.discovery-server:31001/eureka/,http://discovery-server-1.discovery-server:31001/eureka/,http://discovery-server-2.discovery-server:31001/eureka/
eureka.client.registry-fetch-interval-seconds: 5

# ribbon
ribbon.ReadTimeout: 5000
ribbon.ServerListRefreshInterval: 5
ribbon.ConnectTimeout: 1000  #毫秒    连接超时时间
ribbon.OkToRetryOnAllOperations: false    # 是否对所有操作都进行重试
ribbon.MaxAutoRetries: 0     # 对当前实例的最大重试次数(请求服务超时6s则会再请求一次)
ribbon.MaxAutoRetriesNextServer: 0     # 切换实例的最大重试次数(如果还失败就切换下

# feign
feign.compression.request.enabled: true
feign.compression.response.enabled: true
feign.client.config.default.maxConnections: 200
feign.client.config.default.loggerLevel: full
feign.client.config.default.connectTimeout: 1000
feign.client.config.default.readTimeout: 5000
feign.okhttp.enabled: true
feign.hystrix.enabled: false

# hystrix
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
