# server
spring.profiles.active: dev
server.port: 32001
server.http2.enabled: true
server.undertow.worker-threads: 128
server.shutdown: graceful

# eureka
eureka.instance.prefer-ip-address: true
eureka.instance.instance-id: ${spring.cloud.client.ip-address}:${server.port}
eureka.client.serviceUrl.defaultZone: http://discovery-server-0.discovery-server:31001/eureka/,http://discovery-server-1.discovery-server:31001/eureka/,http://discovery-server-2.discovery-server:31001/eureka/
eureka.client.registry-fetch-interval-seconds: 5
ribbon.ServerListRefreshInterval: 5

# timeout
ribbon.ReadTimeout: 5000
feign.client.config.default.readTimeout: 5000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

# zipkin
#spring.zipkin.enable: false
spring.zipkin.base-url: http://zipkin-server:31003

# endpoint
# management.endpoints.web.exposure.include: *

# log
logging.level.root: info
logging.level.com.xxx: debug
logging.file.name: /tmp/server.log
logging.register-shutdown-hook: true
logging.logback.rollingpolicy.total-size-cap: 15MB
logging.file.total-size-cap: 15MB
#logging.logback.rollingpolicy.max-file-size: 11MB
#logging.file.max-size: 11MB

#
test.name: app