# server
spring.profiles.active: dev
server.port: 32001
server.http2.enabled: true
server.undertow.threads.worker: 128
server.shutdown: graceful

# json
spring.jackson.default-property-inclusion: non_null
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
#spring.gson.serialize-nulls: false
#spring.http.converters.preferred-json-mapper=gson

# eureka
eureka.instance.prefer-ip-address: true
eureka.instance.instance-id: ${spring.cloud.client.ip-address}:${server.port}
eureka.client.serviceUrl.defaultZone: http://discovery-server-0.discovery-server:31001/eureka/,http://discovery-server-1.discovery-server:31001/eureka/,http://discovery-server-2.discovery-server:31001/eureka/
eureka.client.registry-fetch-interval-seconds: 5
ribbon.ServerListRefreshInterval: 5

# timeout
ribbon.ReadTimeout: 5000
ribbon.ConnectTimeout: 1000
feign.client.config.default.readTimeout: 5000
feign.client.config.default.connecTimeout: 1000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

# zipkin
#spring.zipkin.enable: false
spring.zipkin.base-url: http://zipkin-server:31003

# endpoint
# management.endpoints.web.exposure.include: *

# log
logging.level.root: info
logging.level.com.xxx: debug
logging.file.name: /tmp/server.log
logging.register-shutdown-hook: true
logging.logback.rollingpolicy.total-size-cap: 16MB
logging.file.total-size-cap: 16MB
#logging.logback.rollingpolicy.max-file-size: 11MB
#logging.file.max-size: 11MB

#
test.name: app
test.name1: name1

# mqtt
mqtt.userName: admin
mqtt.password: password
mqtt.url: tcp://127.0.0.1:1883
mqtt.producer.clientId: mqttProducer
mqtt.producer.defaultTopic: topic1
mqtt.consumer.clientId: mqttConsumer
mqtt.consumer.defaultTopic: topic1

# sentinel
#spring.cloud.sentinel.transport.dashboard: localhost:8719
#spring.cloud.sentinel.datasource.ds1.apollo.namespace-name: application
#spring.cloud.sentinel.datasource.ds1.apollo.flow-rules-key: sentinel.flowRules
#spring.cloud.sentinel.datasource.ds1.apollo.rule-type: flow
#spring.cloud.sentinel.datasource.ds2.apollo.namespace-name: application
#spring.cloud.sentinel.datasource.ds2.apollo.flow-rules-key: sentinel.systemRules
#spring.cloud.sentinel.datasource.ds2.apollo.rule-type: system
#spring.cloud.sentinel.log.dir: logs
#sentinel.systemRules: [ { "qps": 10000 } ]
#sentinel.flowRules: [ { "resource": "/xxx/xxx","count": 1000 } ]

#hystrix.command.default.execution.isolation.strategy: SEMAPHORE
#hystrix.command.default.execution.isolation.semaphore.maxConcurrentRequests: 2
#hystrix.command.default.circuitBreaker.requestVolumeThreshold: 2
#hystrix.command.default.circuitBreaker.enabled: true
#hystrix.command.default.circuitBreaker.forceOpen: true

#spring.main.allow-bean-definition-overriding: true