version: "3"
services:
  nacos1:
    hostname: nacos1
    image: nacos/nacos-server
    volumes:
      - ./logs/nacos1:/home/nacos/logs
      - ./custom.properties:/home/nacos/init.d/custom.properties
    env_file:
      - ./nacos-hostname.env
    restart: always
    networks:
      default:
        ipv4_address: 172.16.16.60

  nacos2:
    hostname: nacos2
    image: nacos/nacos-server
    volumes:
      - ./logs/nacos2:/home/nacos/logs
      - ./custom.properties:/home/nacos/init.d/custom.properties
    env_file:
      - ./nacos-hostname.env
    restart: always
    networks:
      default:
        ipv4_address: 172.16.16.61

  nacos3:
    hostname: nacos3
    image: nacos/nacos-server
    volumes:
      - ./logs/nacos3:/home/nacos/logs
      - ./custom.properties:/home/nacos/init.d/custom.properties
    env_file:
      - ./nacos-hostname.env
    restart: always
    networks:
      default:
        ipv4_address: 172.16.16.62

networks:
  default:
    external:
      name: mynetwork

