version: '3'
services:
  redis:
    container_name: superset_redis
    image: redis
    restart: always
    volumes:
      - redis:/data
  superset:
    container_name: superset
    image: amancevice/superset
    restart: always
    depends_on:
      - redis
    ports:
      - "53182:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
volumes:
  redis: