# 订阅mysql二进制日志，并且发送到kafka
# 1. 先配置DB权限：　
# CREATE database maxwell;
# CREATE USER 'maxwell'@'%' IDENTIFIED BY '123456';
# GRANT ALL ON maxwell.* TO 'maxwell'@'%';
# GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO 'maxwell'@'%';
# flush privileges;
# 2. 修改下面maxwell.properties配置
# 3. 查看日志是否正常: kubectl logs job.batch/maxwell -f -n namespace

# 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: maxwell-config
  #namespace: xx
data:
  maxwell.properties: |
    user=root
    password=mysql_666888.
    host=10.10.10.106
    port=53306
    producer=kafka
    kafka.bootstrap.servers=172.16.16.31:9092,172.16.16.32:9092,172.16.16.33:9092
    kafka_topic=test

---
# 单实例Job
apiVersion: batch/v1
kind: Job
metadata:
  name: maxwell
  #namespace: xx
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: maxwell
        image: zendesk/maxwell
        imagePullPolicy: IfNotPresent
        command: ["bin/maxwell",  "--config=/config/maxwell.properties"]
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: maxwell-config