version: "3"
services:
   wordpress:
     image: wordpress
     ports:
       - "28000:80"
     restart: always
     environment:
       WORDPRESS_DB_NAME: "wordpress"
       WORDPRESS_DB_HOST: "10.10.10.106"
       WORDPRESS_DB_PORT: "53306"
       WORDPRESS_DB_USER: "root"
       WORDPRESS_DB_PASSWORD: "mysql_666888"
     