version: '3.1'

services:
  zk1:
    image: zookeeper
    container_name: zk1
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=172.16.16.22:2888:3888;2181 server.3=172.16.16.23:2888:3888;2181
    networks:
      default:
        ipv4_address: 172.16.16.21

  zk2:
    image: zookeeper
    container_name: zk2
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=172.16.16.21:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=172.16.16.23:2888:3888;2181
    networks:
      default:
        ipv4_address: 172.16.16.22

  zk3:
    image: zookeeper
    container_name: zk3
    restart: always
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=172.16.16.21:2888:3888;2181 server.2=172.16.16.22:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      default:
        ipv4_address: 172.16.16.23

# 引用已经存在网络
# docker network create --subnet=172.16.16.0/24 mynetwork
networks:
  default:
    external:
      name: mynetwork

