server:
  port: 31001

spring:
  application:
    name: discovery-server

#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: false       # 是否使用 ip 地址注册
#    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
#  client:
#    registerWithEureka: false # 注册自己
#    fetchRegistry: false      # 拉取注册信息
#    serviceUrl:
#      defaultZone: http://localhost:31001/eureka/