version: "3"

services:
   hadoop-m1:
     image: th9976/hadoop
     container_name: hadoop-m1
     hostname: hadoop-m1
     volumes:
       - data_m1:/home/data
     deploy:
       mode: global
     environment:
       # slaves: hadoop-s1,hadoop-s2 # hadoop 2
       workers: hadoop-s1,hadoop-s2 # hadoop 3
       start: /usr/local/hadoop/sbin/start-dfs.sh && /usr/local/hadoop/sbin/start-yarn.sh
     depends_on:
       - hadoop-s1
       - hadoop-s2
    # 端口 https://blog.csdn.net/shuoyu816/article/details/90573676
     ports:
       - "58020:8020" # hdfs rpc
       - "59870:9870" # nameNode http
       - "59866:9866" # dataNode http
       - "59864:9864" # dataNode rpc
     tty: true
     stdin_open: true
   
   hadoop-s1:
     image: th9976/hadoop
     container_name: hadoop-s1
     hostname: hadoop-s1
     volumes:
       - data_s1:/home/data
     deploy:
       mode: global
     tty: true  
     stdin_open: true

   hadoop-s2:
    image: th9976/hadoop
    container_name: hadoop-s2
    hostname: hadoop-s2
    volumes:
      - data_s2:/home/data
    deploy:
      mode: global    
    tty: true
    stdin_open: true

volumes:
  data_m1:
  data_s1:
  data_s2:
