apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 3 # in product env 3+
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: th9976/config-server
          imagePullPolicy: IfNotPresent # in product env delete -> default pull
          resources:
            limits:
              memory: 512Mi # jvm limit

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  type: NodePort
  selector:
    app: config-server
  ports:
    - port: 31000
      targetPort: 31000 # node port,in product env  delete
      nodePort: 31000