apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  serviceName: discovery-server
  replicas: 3 # in product env 3+
  podManagementPolicy: "Parallel" # 顺序无关
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: th9976/discovery-server
          imagePullPolicy: IfNotPresent # in product env delete -> default pull
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server-0.discovery-server:31001/eureka/,http://discovery-server-1.discovery-server:31001/eureka/,http://discovery-server-2.discovery-server:31001/eureka/
            - name: JAVA_OPTS_USER
              value: -Deureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
                -Deureka.instance.hostname=${MY_POD_NAME}.discovery-server
                -Deureka.instance.prefer-ip-address=false
                -Deureka.server.use-read-only-response-cache=false
                -Deureka.client.serviceUrl.defaultZone=http://discovery-server-0.discovery-server:31001/eureka/,http://discovery-server-1.discovery-server:31001/eureka/,http://discovery-server-2.discovery-server:31001/eureka/
          resources:
            limits:
              memory: 512Mi # jvm limit
# https://blog.csdn.net/yucaifu1989/article/details/106871375
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - port: 31001
      targetPort: 31001
      nodePort: 31001

