apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  serviceName: discovery-server
  replicas: 3 # in product env 3+
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: th9976/discovery-server
          #imagePullPolicy: IfNotPresent # in product env delete -> default pull
          env:
            - name: "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE"
              value: "http://discovery-server-0.discovery-server:31001/eureka/,http://discovery-server-1.discovery-server:31001/eureka/,http://discovery-server-2.discovery-server:31001/eureka/"
          resources:
            limits:
              memory: 256Mi # jvm limit

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - port: 31001
      targetPort: 31001
      nodePort: 31001

