version: "3"

services:
  apisix-dashboard:
    container_name: apisix-dashboard
    image: apache/apisix-dashboard:2.6
    restart: always
    volumes:
      - ./config_dashboard.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"

  apisix:
    container_name: apisix
    image: apache/apisix:2.5-alpine
    restart: always
    volumes:
      - /data/apisix/log:/usr/local/apisix/logs
      - ./config_apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"

  etcd:
    container_name: apisix-etcd
    image: bitnami/etcd:3.4.15
    user: root
    restart: always
    volumes:
      - /data/apisix/etcd:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"