version: "3"
services:

   mysql:
     image: mysql:5.7
     container_name: mysql
     ports: 
       - "53306:3306"
     volumes:
       - /e/docker/nfs/mysql:/var/lib/mysql
       # chmod 644 ./config/*
       - ./config/:/etc/mysql/conf.d
     #command: --default-authentication-plugin=mysql_native_password
     restart: always
     deploy:
       mode: global
     environment:
       MYSQL_ROOT_PASSWORD: mysql_666888
       MYSQL_DATABASE: test
       MYSQL_USER: test
       MYSQL_PASSWORD: mysql_666888

  #  adminer:
  #   image: adminer
  #   container_name: mysql_admin
  #   restart: always
  #   ports:
  #     - 53308:8080    
# volumes:
#   db_data:
