version: "3"
services:
   mysql1:
     image: mysql:5.7
     container_name: mysql1
     ports: 
       - "53307:3306"
     volumes:
       # chmod 644 ./config/*
       - ./config/:/etc/mysql/conf.d
     #command: --default-authentication-plugin=mysql_native_password
     restart: always
     deploy:
       mode: global
     environment:
       MYSQL_ROOT_PASSWORD: mysql_666888
       MYSQL_DATABASE: test
       MYSQL_USER: test
       MYSQL_PASSWORD: mysql_666888
