server:
  port: 31001

spring:
  application:
    name: discovery-server

eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    #registerWithEureka: false # while singleton set false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-server-0.discovery-server:31001/eureka/,http://discovery-server-1.discovery-server:31001/eureka/,http://discovery-server-2.discovery-server:31001/eureka/